[package]
name = "HERDAOWorkshop"
version = "0.1.0"
description = "A workshop for building smart contracts with Cairo 1.0"
homepage = "https://github.com/omarespejel/HERDAO-Cairo"

[[target.starknet-contract]]
name = "contracts"